# Stable features
max_width = 100
use_field_init_shorthand = true
newline_style = "Unix"
edition = "2021"
reorder_imports = true
reorder_modules = true
use_try_shorthand = true

# Unstable features (nightly only)
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
format_code_in_doc_comments = true
format_strings = true
