[package]
name = "highlighting"
version = "0.0.1"
edition = "2021"

[dependencies]
owo-colors = "4.0.0"
syntect = { version = "5.1.0", default-features = false, features = ["default-syntaxes", "default-themes", "default-onig"] }
